### ISSUE TITLE
GetVOD does not work 

### ISSUE THREAD

**Issue by hejoseph** [dudik/twitch-m3u8#17]
i have this error when using getVOD:

Error: Twitch returned status code 403
    at IncomingMessage.<anonymous> (/sandbox/node_modules/twitch-m3u8/index.js:78:14)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**Comment by MikeMilzz** [comment]
It seems that Twitch has disabled a number of APIs that this, and a few other solutions, use to get the HLS stream URL. I haven't found any working solution that gets around these disabled API endpoints.

**Comment by QuentinPhrl** [comment]
Same issue

**Comment by nagualcode** [comment]
> It seems that Twitch has disabled a number of APIs that this, and a few other solutions, use to get the HLS stream URL. I haven't found any working solution that gets around these disabled API endpoints.

what is streamlink doing?
